<? foreach($this->products as $product):  ?>
<div class="row-fluid productitem clearfix">
    <div class="span7">
        <h4><a href="<?=$this->url(array('productIdent' => $product->ident, 
                                   'categoryIdent' => $this->categoryIdent),
                                   'catalog_category_product'); ?>"><?=$this->Escape($product->name); ?></a></h4>
        <p><?=$this->Escape($product->shortDescription); ?></p>
        <p><?=$this->productPrice($product); ?></p>
        <?=$this->Cart()->addForm($product); ?>
    </div>
    <div class="span4">
        <?=$this->productImage($product->defaultImage, array('class' => 'right'))->thumbnail(); ?>
    </div>
</div>
<? endforeach; ?>

<!--? if($this->products instanceof Zend_Paginator): ?>
<!--?= $this->paginationControl($this->products,
                             'Sliding',
                             'catalog/_paginator.phtml'); ?>
<!--? endif -->
