<h3 id="ajax-cat-name"></h3>
<p id="ajax-bread">
</p>
<div id="dyna-products">
    <img src="<?=$this->baseUrl()?>/images/icons/preloader-icon.gif">
</div>
<script>
    console.log('calling dynaproducts');
    $('#dyna-products').load(
        '<?=$this->baseUrl()?>/catalog/dynaproducts',
        <?=json_encode($this->products)?>
    );
        
    $.ajax(
        '<?=$this->baseUrl()?>/catalog/ajaxcategory',
        {
            data: <?=json_encode($this->products)?>,
            success: function(retData) {
                $('#ajax-cat-name').html(retData.catName);
                $('#ajax-bread').html(retData.bread);
                $('#ajax-sub-cats').html(retData.subCats);
            }
        }
    );

</script>
