<?php global $logger; ?>
<?= $this->doctype() ?>

<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en">
<head>
    <?= $this->headTitle() ?>
    <?= $this->headMeta() ?>
    <?= $this->headStyle() ?>
    <?= $this->headLink() ?>
    <?= $this->headScript() ?>
</head>
<body>
    <div class="container">
    <?php include('zstore-header.phtml'); ?>
    <br />    
    <div id="contentWrap" class="clearfix">
        <?= $this->layout()->content ?> 
    </div>
    
    <div id="footer" class="clearfix">
        <div class="left">
            <span class="rss"><a href="/rss" title="products feed">RSS 2.0</a></span>
        </div>
        <div class="right">
            &#169; 2013 Abidimi Inc.
        </div>
    </div>
    </div>
    <?=$this->inlineScript()?>
</body>
</html>
