<?= $this->doctype() ?>
<?php global $logger; ?>

<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en">
<head>
    <?= $this->headTitle() ?>    
    <?= $this->headMeta() ?>
    <?= $this->headStyle() ?>
    <?= $this->headLink() ?>
    
    <?= $this->headScript() ?>
    
</head>
<body>
    <div class="container">
    <?php include('zstore-header.phtml'); ?>
    <br />
    <div id="contentWrap" class="row">
        <div class="left categorylist span3">
            <div class="sub-nav">
            <h3>select <span>category</span></h3>
                <ul id="dyna-top-cats">
                    <img src="<?=$this->baseUrl()?>/images/icons/loading.gif">
                </ul>
            </div>
            <script>
            $(document).ready(function() {
                console.log('loadhtmltopcategories');
                $('#dyna-top-cats').load(
                    '<?=$this->baseUrl()?>/catalog/loadhtmltopcats'
                );
            });
            </script>
        
            <div id="ajax-sub-cats" class="sub-nav"></div> 
            <div>
                <h3>in your <span>cart</span></h3>
                <?= $this->Cart()->getSummary(); ?>
            </div>
        </div><!--.catagorylist (left column) -->
        <div class="content left span8">
            <?= $this->layout()->content ?> 
       </div>
    </div> <!--#contentWrap-->
    
    <div id="footer" class="clearfix">
        <div class="left">
            <span class="rss"><a href="/rss" title="products feed">RSS 2.0</a></span>
        </div>
        <div class="right">
            &#169; 2013 Abidimi Inc.
        </div>
    </div>
    </div>
    <?= $this->inlineScript() ?>
</body>
</html>